# -*- coding: utf-8 -*-
"""trashdetect-model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GKAWPm3N403CWToruBMcoxCVAtmRGlQw
"""

!nvidia-smi

!unzip -q /content/data.zip -d /content/data

import shutil

folder_path = "/content/data/__MACOSX"

shutil.rmtree(folder_path)

import shutil
import os

src_folder = "data/data.yaml"
dst_folder = "content"

for item in os.listdir(src_folder):
    src_path = os.path.join(src_folder, item)
    dst_path = os.path.join(dst_folder, item)

    shutil.move(src_path, dst_path)

!pip install ultralytics

!ls -R /content

from google.colab import drive
drive.mount('/content/drive')

!yolo detect train data=data.yaml model=yolo11s.pt epochs=50 imgsz=640

!yolo detect predict model=runs/detect/train3/weights/best.pt source=data/valid/images save=True

import glob
from IPython.display import Image, display
for image_path in glob.glob(f'/content/runs/detect/predict/*.jpg')[:50]:
 display(Image(filename=image_path, height=400))
 print('\n')

!pip install ultralytics opencv-python

from ultralytics import YOLO
import cv2
import torch


model = YOLO("/content/runs/detect/train3/weights/best.pt")

import shutil

folder_path = "/content/my_model"
shutil.rmtree(folder_path)
print(f"✅ Папка {folder_path} удалена")

# Commented out IPython magic to ensure Python compatibility.
!mkdir /content/my_model
!cp /content/runs/detect/train3/weights/best.pt /content/my_model/my_model.pt
!cp -r /content/runs/detect/train3 /content/my_model

# %cd my_model
!zip /content/my_model.zip my_model.pt
!zip -r /content/my_model.zip train3
# %cd /content

